#!/bin/sh

cmd=$(which tmux)
session=halo

if [ -z $cmd ]; then
    echo "You need to intall tmux."
    exit 1
fi

$cmd has -t $session

if [ $? != 0 ]; then
    $cmd new -d -n zsh -s $session "zsh"
    # $cmd neww -n goagent -t $session "python2 /home/hbc/workshop/goagent/local/proxy.py"
    $cmd selectw -t $session:1
fi

$cmd att -t $session

exit 0
